# -*- coding: utf-8 -*-
"""TORCH_DS_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1adE7qIFIEsC-Nj7ZXuxfdpgc6jQ-VTqf
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

df = pd.read_csv('/content/population.csv',  encoding='utf-8')
df.head()

df_final = df.drop(['Country Code',	'Indicator Name',	'Indicator Code'], axis=1)

chosen_country = 'United States'


country_data = df_final[df_final['Country Name'] == chosen_country]


years = country_data.columns[2:].astype(int)
population = country_data.iloc[:, 2:].values.flatten()

plt.figure(figsize=(5, 3))
plt.bar(years, population, color='skyblue')
plt.xlabel('Year')
plt.ylabel('Population')
plt.title(f'Population of {chosen_country} Over the Years')


plt.show()

plt.hist(population, bins=20, color='skyblue', edgecolor='black')
plt.show()

